[workspace]
members = ["sony-wf1000xm5", "controller-gui"]
resolver = "3"

[profile.superopt]
inherits = "release"
codegen-units = 1
lto = "fat"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
